-- Core schema for GymApp

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE nutrition_targets (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    item       VARCHAR(255) NOT NULL,
    value      VARCHAR(255),
    note       TEXT,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_nutrition_targets_user ON nutrition_targets (user_id);

-- Default nutrition targets copied into a new user's account on registration
CREATE TABLE nutrition_target_templates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item       VARCHAR(255) NOT NULL,
    value      VARCHAR(255),
    note       TEXT,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE workout_programs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    duration_days INT NOT NULL DEFAULT 60,
    start_date    DATE,
    status        VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    is_template   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workout_programs_user ON workout_programs (user_id);

CREATE TABLE workout_days (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id    BIGINT NOT NULL REFERENCES workout_programs (id) ON DELETE CASCADE,
    day_number    INT NOT NULL,
    week_number   INT,
    day_of_week   VARCHAR(20),
    training_type VARCHAR(255),
    rest_advice   VARCHAR(255),
    cardio        TEXT,
    notes         TEXT,
    CONSTRAINT uq_workout_days_program_day UNIQUE (program_id, day_number)
);

CREATE TABLE workout_exercises (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_day_id BIGINT NOT NULL REFERENCES workout_days (id) ON DELETE CASCADE,
    sort_order     INT NOT NULL DEFAULT 0,
    name           VARCHAR(255) NOT NULL,
    sets_reps      VARCHAR(255)
);

CREATE INDEX idx_workout_exercises_day ON workout_exercises (workout_day_id);

CREATE TABLE meal_plans (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    duration_days INT NOT NULL DEFAULT 60,
    is_template   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_meal_plans_user ON meal_plans (user_id);

CREATE TABLE meal_days (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id    BIGINT NOT NULL REFERENCES meal_plans (id) ON DELETE CASCADE,
    day_number      INT NOT NULL,
    week_number     INT,
    day_of_week     VARCHAR(20),
    breakfast       TEXT,
    lunch           TEXT,
    afternoon_snack TEXT,
    dinner          TEXT,
    supplements     TEXT,
    tips            TEXT,
    CONSTRAINT uq_meal_days_plan_day UNIQUE (meal_plan_id, day_number)
);

CREATE TABLE day_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    program_id    BIGINT NOT NULL REFERENCES workout_programs (id) ON DELETE CASCADE,
    day_number    INT NOT NULL,
    completed     BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at  TIMESTAMP,
    workout_notes TEXT,
    CONSTRAINT uq_day_logs_program_day UNIQUE (program_id, day_number)
);

CREATE INDEX idx_day_logs_user ON day_logs (user_id);

CREATE TABLE weekly_reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    program_id          BIGINT NOT NULL REFERENCES workout_programs (id) ON DELETE CASCADE,
    week_number         INT NOT NULL,
    log_date            DATE,
    weight_kg           NUMERIC(5, 2),
    waist_cm            NUMERIC(5, 2),
    strength_progress   TEXT,
    mood_sleep_soreness TEXT,
    reflection          TEXT,
    CONSTRAINT uq_weekly_reviews_program_week UNIQUE (program_id, week_number)
);

CREATE INDEX idx_weekly_reviews_user ON weekly_reviews (user_id);
