-- Personal libraries (reusable workout activities and meal dishes) + per-exercise progress

CREATE TABLE workout_activities (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category   VARCHAR(255),
    name       VARCHAR(255) NOT NULL,
    notes      TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workout_activities_user ON workout_activities (user_id);

CREATE TABLE meal_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name           VARCHAR(255) NOT NULL,
    cooking_method TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_meal_items_user ON meal_items (user_id);

-- Per-exercise completion within a workout day (one row per exercise instance)
CREATE TABLE exercise_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT NOT NULL UNIQUE REFERENCES workout_exercises (id) ON DELETE CASCADE,
    completed          BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at       TIMESTAMP
);
